defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: oinvertedworld/entrypoint_test:latest

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: 
          shell: /bin/bash --login -eo pipefail
          command: |
            groundhog --version

workflows:
  version: 2
  build_deploy:
    jobs:
      - build