defaults: &defaults
  working_directory: ~/repo
  shell: /bin/bash --login -eo pipefail
  docker:
    - image: oinvertedworld/entrypoint_test_alt

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          command: |
            groundhog --version

workflows:
  version: 2
  build_deploy:
    jobs:
      - build